"""
Utility variables and configuration for the simulation backend.
This file is required by the project but not included in the repo —
users must create it manually (or it's generated by the setup script).
"""

import json
from pathlib import Path

# --- OpenAI / LLM config ---------------------------------------------------
config_path = Path(__file__).resolve().parent.parent.parent / "openai_config.json"
with open(config_path, "r") as f:
  _config = json.load(f)

openai_api_key = _config.get("model-key", "")
use_openai = _config.get("client") in ("openai", "zhipu", "azure")
api_model = _config.get("model", "")

# --- Debug flag -------------------------------------------------------------
debug = True

# --- File-system paths ------------------------------------------------------
# These are relative to the working directory when running the backend,
# which is  reverie/backend_server/
_base = Path(__file__).resolve().parent.parent.parent

maze_assets_loc = str(_base / "environment" / "frontend_server" / "static_dirs" / "assets")
env_matrix = str(_base / "environment" / "frontend_server" / "static_dirs" / "assets" / "the_ville" / "matrix")
fs_storage = str(_base / "environment" / "frontend_server" / "storage")
fs_temp_storage = str(_base / "environment" / "frontend_server" / "temp_storage")

# --- Collision block id (used in path-finding) ------------------------------
collision_block_id = "32125"

# --- MQTT config (optional, for real-time visualization) --------------------
mqtt_host = "localhost"
mqtt_port = 1883
mqtt_client_id = "reverie-backend"
mqtt_movement_topic = "movement"
mqtt_environment_topic = "environment"
